FROM python:3.13-slim

RUN apt-get update && apt-get install -y \
    curl \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin/:$PATH"

COPY . /app

EXPOSE 8000

CMD ['run', 'uvicorn', 'run:app.main:app', '--host', '0.0.0.0', '--port', '8000']